### ISSUE TITLE
OTel not loaded!

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/Office-Addin-TaskPane-Angular#44]
Hi everyone!

I hope you're doing well! I built an Excel task pane add-in using Angular from the given template and didn't even write or modify any code. However, after uploading the manifest file, I got an error message regarding "OTel not loaded!" from excel-web-16.00.js file (a CDN from Microsoft). So, I was wondering if you guys could let me know how to fix this problem or help me out.

Attached is a screenshot of this error.

Thank you for your time and consideration!

![Screen Shot 2562-10-15 at 17 36 17](https://user-images.githubusercontent.com/18175994/66824954-78e40e00-ef73-11e9-84e7-f2b4bf239c5f.png)

**Comment by millerds** [comment]
If you are still having trouble with this please re-open.
