### ISSUE TITLE
Will upgrading the angular version causes any problem while publishing the Add-in?

### ISSUE THREAD

**Issue by Vrushi007** [OfficeDev/Office-Addin-TaskPane-Angular#46]
I have created a add-in for outlook through yomen generator. For some reasons, I updated the angular version from 5.2.9 to 8.2.12.
The add-in is working fine in development mode.
But, when the add-in is published, I'm getting errors.
Is this the problem?

**Comment by aagamdoshi** [comment]
@Vrushi007 are you successfully able to debug the application on web? Whenever i try to navigate to web with https:localhost:3000/ i get to see the file structure and not the site, when i try to open taskpane.hyml by navugation , it says please sideload your addin.

Need help.

**Comment by wellington-santana** [comment]
Same here @aagamdoshi =/

**Comment by Vrushi007** [comment]
I've made some changes in webpack. Now, the addin is working great in production mode too.

**Comment by aagamdoshi** [comment]
Can you share the steps or reference to the changes done for web pack
