### ISSUE TITLE
Issues in Debugging directly on Web and VS 2019

### ISSUE THREAD

**Issue by aagamdoshi** [OfficeDev/Office-Addin-TaskPane-Angular#51]
I am not able to view/debug the application on web, although it shows its hosted on localhost:3000 and works for Word Desktop application? 
Whenever i try to navigate to web with **https:localhost:3000/** I get to see the file structure and not the site, when i try to open taskpane.html by navigation , it says please side load your addin.

Also i wanted to know how can this solution be debugged via Visual Studio 2019 , as when i try to do, it says symbols are not loaded.

So its not working directly on web and not on VS 2019 as mentioned

Need help.

**Comment by millerds** [comment]
If you still need help please re-open.
