### ISSUE TITLE
Taskpanes, Manifests, and Routing?

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/Office-Addin-TaskPane-Angular#65]
Hi,

I have noted two Microsoft projects out on GitHub:

https://github.com/OfficeDev/Office-Addin-TaskPane

https://github.com/OfficeDev/Office-Addin-TaskPane-Angular

I am presently trying to implement an Outlook web add-in with Angular that is embedded within an ASP.Net MVC application. For example, imagine that the taskpane displays the web app's login and, after logging into the web app, it redirects back to a taskpane.html or index.html.

I also saw this blog article that seemed to recommend not using the webpack.config with Angular:

https://www.initgrep.com/posts/javascript/angular/microsoft-office-addin-using-angular-cli

In my case, the web app works as expected within the browser. When loaded within the taskpane, there are content security policy or CORS / CORB errors and it won't load. The former I commented out in the ASP.Net web.config but even after implementing a couple of Chrome extensions, it still gets blocked on Chrome, for example.

Within the desktop application, the add-in loads and the ASP.Net login works but the very basic example scripts do not run which are from one of the Microsoft Outlook add-in samples which extract text from an Outlook message. 

When run as a straight Angular add-in, it works as expected. However, we won't be running this within the desktop application; only doing so for testing.

I believe the situation is further complicated when embedded or served up by an ASP.Net solution due to its own routes and controllers. I’ve not found any documentation which details an approach or best practices in relation to combining an external website with Office web add-in taskpanes.

Any thoughts?

Big Thanks,

**Comment by millerds** [comment]
A better place to get help on this would be https://docs.microsoft.com/en-us/answers/index.html or stackoverflow
