### ISSUE TITLE
How to run desktop Word AddIn with Angular 11.0.5 in MS office 2016

### ISSUE THREAD

**Issue by vinodifour** [OfficeDev/Office-Addin-TaskPane-Angular#66]
# I'm trying to load my add-ins in office but not working. it's work fine in online platform. I'll try With Angular 5.2.11 and MS Word 2016 my AddIn working fine when upgrading the version of angular to 11.0.5 after that Add-in does not load. below is my environment detail and code link can any one help me.

[Here is my code](https://drive.google.com/file/d/1sftv5yFuH7yzyQHC34oH52wxopHR8KgP/view)

**Additional Details :**
- AddIn working fine with Word online version
- Add-in does not load with MS Word 2016/2019/365 desktop version after upgrading to latest angular version.

**Environment detail :**

- PC Desktop : Windows 10
- Browser on Web - Microsoft Edge, Mozila Firefox
- Office version - 2016/2019, office 365
- 64 bit Operating System

Image for after running project [Desktop addin image](https://drive.google.com/file/d/1DjH8soLOyEz_KIbP17oEQJA2HE3_iUsW/view?usp=sharing)

**Comment by metaloha** [comment]
I've created a repo at https://github.com/metaloha/office-angular that is this for Angular 11.x 😄 You will likely need to start from scratch though, since there isn't really a direct upgrade path from the version 5 used in this repo (but most of your code should be copy/pasteable).

**Comment by igor-ribeiiro** [comment]
We will be looking to upgrade our templates. Fell free to reopen this issue if you still need help
