### ISSUE TITLE
No option to open hyperlink in Word add-in in Office 2019

### ISSUE THREAD

**Issue by ShahViral6438** [OfficeDev/Office-Addin-TaskPane-Angular#79]
# Expected behavior

Word add-in should show an option to open hyperlink in Office 2019.

# Current behavior

I am having word add-in, built using Angular 12, TypeScript and Telerik Kendo controls. When I open the same add-in in Office 2019 and creates a link in the Editor, I don't see option "Open link in new Window" when I right click on the link. Same option is visible in Office 365. Hence I am suspecting this is something related to IE browser and add-in behavior in Office 2019.

I have attached images of different behavior of right click context menu in both Office 365 and Office 2019 versions.

<img width="482" alt="kendo-editor-right-click-issue" src="https://user-images.githubusercontent.com/36051026/133606872-9afe6af3-bdcd-4e48-a235-a7231ed61fef.png">

<img width="250" alt="link-rightclick-in-O365" src="https://user-images.githubusercontent.com/36051026/133606876-c9c7aae9-8ac1-435b-8100-a18aa394251d.png">

Any help or pointers will be much appreciated.

**Comment by millerds** [comment]
Different control are used to provide the content in office based on the version of office and OS you are running on.  The control swill behave differently.

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by millerds** [comment]
If there are any further comments or questions please re-open.
