### ISSUE TITLE
Add In SideLoading Error (Not signed message)

### ISSUE THREAD

**Issue by tobiashoeft** [OfficeDev/Office-Addin-TaskPane-Angular#94]
I did a sideload to test my add-in. I received the following error message:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/5573898/174777532-92d43388-761b-4774-af72-449a97a4695e.png">

The Application is hosted on a web server via. SSL. To test it before it goes production. 

What am i missing? 

The manifest is valid.

**Comment by millerds** [comment]
Can you translate the error to English?

**Comment by tobiashoeft** [comment]
The content is blocked because it was not signed with your valid security certificate

**Comment by millerds** [comment]
Can you run 'npx office-addin-dev-certs verify' and let me know the results?

**Comment by tobiashoeft** [comment]
Hi, thx for reply. 

You have trusted access to https://localhost.
Certificate: C:\Users\tobii\.office-addin-dev-certs\localhost.crt
Key: C:\Users\tobii\.office-addin-dev-certs\localhost.key

**Comment by tobiashoeft** [comment]
Okay thx you.

**Comment by millerds** [comment]
The certificate is just for local development (serving the add-in from localhost).  Once your add-in is hosted in a production environment then you updated the manifest to point to that location and anyone loading using that manifest will not need the certificate.
